using Dalamud.Bindings.ImGui;
using System;
using System.Numerics;

namespace HuntHelperEvolved;

public sealed partial class Plugin
{
    private string _helpSearch = string.Empty;
    private static readonly (string Title, string Text)[] HelpTopics =
    [
        ("Manual S-rank mapping",
            "Shift-click an S-capable spawn point to toggle a shared manual exclusion. Or select a mark in S-ranks > Mapping, or click the point count in /hhs, to compare coordinates, choose Manual, Faloop, Bear or Other as the source, and uncheck points that cannot host the S. Recheck to undo a manual exclusion; automatic A/B evidence and the previous S spawn remain protected. Entries apply only to the selected world, instance and kill cycle, and reset on the next S kill. Sharing requires a server with manual-mapping support. These controls record your input; they do not automatically import Bear or Faloop maps."),
        ("Getting around",
            "The main window has four views: Train, Active Marks, A-rank Timers and S-ranks. Train keeps its route visible while Plan or Reports is open alongside it, or above it in a narrow window. Select an S-rank to see its overview, mapping, counters and eligible train watches in the same world and instance. All counters opens the full stored-counter browser. Settings opens a separate window with visible categories and search; closing it returns to your current task. Tally opens the full lifetime tally. The compact /hht train and /hhv Active Marks windows stay independent of the main navigation, with shared underlying hunt data and train state. Appearance settings select Graphite, Daylight or the Dalamud theme. The Windows menu under More opens standalone boards and popouts. The plugin installer lists the /hh command family when Hunt Helper is absent, or the /htr family when installed (including disabled copies). Extra aliases remain usable when not held by another plugin. Changes save as you edit.\n\n" +
            "Commands: /hh opens the main window; /hht the train; /hht on and /hht off (also /htrt on/off) control automatic train following; /hhc the trigger counters; /hhs the S-rank timers; /hha the A-rank timers; /hhv or /hhsa Active Marks; /hhtally or /hunttally the lifetime tally. /hhn flags the next live train mark; /hhna names its nearest aetheryte; /hhm or /htrm toggles map controls."),
        ("Train controls, scouting and reports",
            "Follow beside the scouting play/pause control in Train and /hht controls automatic next-mark flags and their chat echoes. /hht on and /hht off do the same. This local choice is saved across reconnects and reloads; it starts on for existing users. Scouting, sharing and manual Next Mark, row flags and travel remain available when off. The auto-advance preference in Settings > Train also applies when following is on. Turning following on resumes from the current route without replaying missed marks.\n\n" +
            "Scouting starts paused after login. Use the play/pause control to resume and join scout credits and pick up new marks. Pause stops new records; existing health and death reports still update. Next mark selects, flags and announces the next live mark without recording a kill. Next Aetheryte announces and copies its destination without teleporting or moving the flag. The aetheryte icon beside each mark travels to its nearest destination; travelling to a rally stop completes it after a short delay. Click a mark's text to flag it; chat echo is optional. The check, crosshairs and remove icons sit on the right. The check records a witnessed kill now; on dead rows an undo arrow restores the mark. Crosshairs records found gone without inventing a kill time; clearing that evidence leaves the mark dead with an unknown time. Hold Ctrl and click the remove icon to remove the row. Train view includes Show spicing markers, the same preference as Settings > Train. When enabled, right-click the mark row and choose Being spiced.\n\n" +
            "World headings keep marks from different worlds separate. While scanning is active, Route and /hht offer a preset dropdown, followed by Add Flag and an optional name box. Pausing replaces those controls with the current order and a Change shortcut to Plan; it does not clear the preset or optional name draft. Add Flag adds your current map flag as a custom stop. Choosing or reselecting a preset resumes its ordering and rally stops. Plan > Calculate Rally Flags updates pending rallies from the current train order using the paused preset's rally settings. It keeps mark order and the pause, and does not restart completed rallies. It is disabled for Manual order or an active preset; shared trains need server 0.3.31 or later. Plan also contains preset management, Group expansions within worlds and Open next automatically, plus import/export and the same Add Flag controls. The optional name draft is shared between the main window and /hht. Drag rows within their world/expansion or drag a heading to reorder expansions within one world. Recorded totals exclude rally stops and remain stable when dead rows are hidden. Hide dead changes the display; Remove Dead removes rows but retains report history. Imports merge and export codes retain worlds, instances and custom stops.\n\n" +
            "Plan also manages scout credits. Type a manual name, then press Enter or Add scout to share it; unsubmitted name drafts stay local. Plan and Reports in /hht open inside the compact window without opening the main workspace. Click End train to review completion, or hold Shift and click it to send directly. Completing the last leg clears credits and removed-name suppression and pauses scouting; partial reports keep the remaining train's credits. Reports offers Scouting report and Train completion, with the relevant Shift-click send button below the preview. Webhook progress and results appear on Reports, and /hht keeps a compact result line beneath its route totals. Conflicting train edits are disabled while posting; Next Mark and Next Aetheryte remain usable.\n\n" +
            "Train completion clears reported dead marks only after Discord success and, for shared trains, server acknowledgement. Unfinished legs remain. Failed submission or concurrent edits retain the train. If acknowledgement is lost, inspect state before posting again. Plan > Recovery contains Shift-click Reset train, which posts nothing, and Undo reset. Undo restores locally and turns train sharing off without replacing your friends' train; a recovery notice also appears beside the route after a reset."),
        ("Scout notes and report preview",
            "Reports > Scouting report shows an optional note of up to 256 Unicode code points, credited scouts and the outgoing content. The draft stays local until sent and lasts for the current plugin session. Closing a window or changing page keeps it. A successful send clears only the submitted draft; failures or partial delivery retain it, and edits made during sending are kept for the next report.\n\n" +
            "A reset or replacement train, including a shared snapshot on joining or reconnecting, detaches an unsent note so it is not automatically included in the new report. Previous note lets you explicitly reuse or discard it. Local Undo reset can restore the draft when no newer edit would be overwritten.\n\n" +
            "Scouting reports group last recorded state by world and expansion, with compact remaining/expected counts such as 1/12 for a partial scout. Totals use the full expansion roster and known instances per zone from server metadata or scout records; three instances across all six zones give 36 expected marks. Marked snipes, witnessed kills and unknown deaths remain distinct; Not recorded means absent from the retained list, not proof a mark is absent in an instance. The intact import code comes first, followed by the summary, notes and scout credits in one card within one Discord message when they fit. Otherwise, the code is sent first and the report second. The preview shows the count; if either part exceeds its own limit, nothing is sent and the draft is kept. Sending refreshes the current train snapshot. While posting, the preview shows the captured report and new note edits wait for the next one. Completion reports retain their separate respawn-window summaries and individual history."),
        ("Automatic train watches",
            "Train > Plan > S-rank watch setup can automatically follow open timer windows for Tyger, Ophioneus, Narrow-rift and Neyoozoteel in the train's worlds, zones and instances. Eligible marks also offer Train watch in their selected S-rank details. Enable automation on the client preparing the train. Manual watches and recorded check results are preserved; unchecked automatic watches are removed when no longer eligible. Turn automation off before removing an automatic watch yourself. Shared automation needs an updated server. Watch results remain available under the route while conducting.\n\n" +
            "A confirmed mapped point supplies coordinates and a reminder map link; no point is guessed. Reminders only fire in the train's world and instance, not when visiting another world. Completed checks do not remind again. Reminder preferences live in Settings > Train."),
        ("Map overlays and S-rank mapping",
            "Spawn points show possible locations; live dots show marks currently seen by you or the group. Rank filters for points and live marks are independent. Hold Alt and left-click a spawn point to flag it when enabled; ordinary clicks do not flag it. SS event locations use the same shortcut. Ctrl still hides the overlay, and Shift-click still toggles manual S-rank exclusions on supported points. Names and HP follow live-mark filters. Remote observations expire after three seconds without updates.\n\n" +
            "Dim points for found A-ranks, in Settings > Map & overlays and the map bar, dims points used only by living, non-sniped A-ranks already in your train, including their S-rank candidate rings. It runs only while scanning, when some but not all of the zone/instance's A-ranks are alive in the list. Dead or sniped rows do not count as found: Li'l Murderer alive with Huracan sniped still dims Li'l-only points, while both alive or both sniped keeps all points normal. Shared points stay normal if a possible mark is missing; unknown assignments stay normal too. Pausing, removing the living mark or marking it dead/sniped restores its points. Living train locations, enabled B-rank points and confirmed S-rank fills keep their usual appearance.\n\n" +
            "Gold outlines indicate possible S-rank spots. A/B sightings rule out their spots for the current reliable S-kill cycle, and the previous S death spot is excluded. A confirmed final point is filled gold. Adjust outline width and colour in Settings > Map & overlays. Optional dark dot outlines add contrast and move the gold ring outside the dot; they default to off to preserve the original appearance.\n\n" +
            "Player guides include the detection circle, projected path, heading line and player dot. The radius scale changes their display. The map control bar toggles these layers quickly. SS overlays show event minion locations and the mark spawn location during an event."),
        ("Timer tables, colours and conditions",
            "Click a data-column header to cycle ascending, descending and automatic order. Right-click headers to choose columns. Unknown values sort last. World and expansion filters accept multiple selections; A-rank instances stay separate. Uninstanced cells are blank. Hide unmet conditions removes red condition states while keeping green, yellow and grey states.\n\n" +
            "In /hha, Ctrl-click a mark name to travel to its zone with Lifestream. Last known location uses the latest coordinates reported by anyone in the sync group, including the current location when the mark is seen up. Positions remain available after trains clear and stay separate for each world and instance. Server 0.3.32 or later supplies saved positions when joining after a train has cleared. Unavailable locations are greyed out. A saved position alone does not confirm a new spawn.\n\n" +
            "The progress bar measures elapsed respawn-window time, not spawn probability. S-rank names are grey before readiness or when unknown, red when the respawn window is open but timed conditions are unmet, and green when both align. Hover the Conditions cell for the mark's spawn requirements. The condition timer uses real time and counts down to opening or closing. Required kills, gathering and player actions still apply; their completion is not verified. Unknown or uncertain kill times cannot confirm spawn availability. Use the travel icon or Ctrl-click a name to travel; hover the name for its travel hint without holding Ctrl. Both the main S-rank workspace and /hhs have direct travel icons.\n\n" +
            "Active S ranks have red rows and appear first in automatic order. Active A ranks retain their usual row background. Available-only filtering retains active S ranks; it does not perform spawn actions for you. An uncertain kill cannot establish a precise window; sniped A-rank bounds use the previous live sighting when known.\n\n" +
            "In /hhs, the Record column has a check to record a kill now, a minutes-ago input and clock to apply it, and an eraser to clear the recorded kill. Hold Shift for destructive clear actions. The selected S-rank overview offers the same recording choices. Maintenance timing comes from the server's Faloop restart feed. Offline worlds are crossed out while restart clocks continue. The Connection icon in /hh shows connection, Faloop freshness and feed coverage."),
        ("Active Marks",
            "Rank controls show All/S/A/B marks. Green means alive and unpulled, amber pulled, red dead, blue a community report without live feedback, and grey unknown combat state. HP follows the name; ?% means unknown. The line includes zone and a nearby-player count in brackets. Faloop reports also show elapsed active time.\n\n" +
            "Nearby counts estimate players within 50 yalms, including the scout. Cached positions include players no longer rendered; unseen departures can remain counted until the cache resets on zone, world, instance or logout. The largest fresh count from observers is shown; counts are not added together. [?] means no count is available.\n\n" +
            "Click a mark for its map. Ctrl-click travels with Lifestream to the world, nearest eligible aetheryte and reported instance; right-click opens actions. Open Filters in the window or Settings > Active Marks to add scope rules. Each rule has its own ranks, expansions and world/data-centre selection; a mark appears when it matches any enabled rule. For example, show S ranks across Crystal and A ranks only on Mateus, then add a Shadowbringers rule for other data centres. Source and status filters apply to every rule. With no enabled rules, the list is empty.\n\n" +
            "Current World follows the world you are visiting, and Current Data Centre follows its data centre. These scopes show no marks while your current world is unavailable during loading. Filters are shared by the main Active Marks view and /hhv; each keeps its own search and rank tab. An optional data-centre label helps distinguish worlds. After your first login, this window can remain open through DC travel."),
        ("Notifications and message templates",
            "Settings > Notifications contains local detection chat, speech and fly-text channels plus group/Faloop S-rank alerts. Rank toggles control local channels. FOUND identifies your detection; RELAY identifies a shared report. Your own detection should not produce a duplicate relay.\n\n" +
            "S-rank RELAY chat and its sound follow independent world/DC and expansion rules in Settings > Notifications. Current world and Current DC follow you when travelling. NA hunt mix selects all S ranks on Crystal and ShB/EW/DT S ranks on Aether, Primal and Dynamis. Copy /hhv S-rank rules makes a separate copy; display and notification settings remain independent. Server coverage still applies. Historical snapshots do not trigger alerts. Test chat format shows a local TEST example using sample coordinates, ignores the chat-alert switch and relay rules, and sends no report to the server.\n\n" +
            "Message placeholders: <name>, <rank>, <hpp> (health) and <flag> (map link). Icons: <goldstar>, <silverstar>, <warning>, <nocircle>, <alarm>, <notoriousmonster>, <exclamationrectangle>, <priorityworld>, <elementallevel>, <fanfestival>, <controllerbutton0> and <controllerbutton1>. Speech reads name, rank and health while omitting flags/icons, and requires an available system voice. Brief hover labels remain on icon controls; live status and mark-specific details remain available where useful."),
        ("Reset settings",
            "Settings > Reset restores defaults by category or all preferences at once. Map display, map colours and player guides are separate groups. Each reset describes its scope and asks for confirmation. Trains, presets, counter totals, tally totals and achievement baselines are kept.\n\n" +
            "Resetting train preferences restores expansion grouping and order without removing marks. Resetting window filters clears searches while keeping windows open. Resetting tally preferences restores the history limit; older detail entries may be trimmed as new kills are recorded.\n\n" +
            "Sharing resets and reset-all turn sync off but keep your connection details and Discord destinations. Clear saved connections has separate actions for removing a saved sync connection or Discord destinations. These do not send messages or clear the group's train."),
        ("Travel",
            "Lifestream handles world and aetheryte travel from Active Marks and Ctrl-clicking S-rank or A-rank names. The A board uses the latest local or shared location, or the zone centre when none is known. If no exact position is known, the S board chooses a destination suitable for a spawn attempt. When an instance is reported, travel selects it after reaching the aetheryte.\n\n" +
            "Settings > Travel excludes aetherytes from routing. Teleport also drops the map flag is configured with train actions. Unavailable Lifestream or a missing allowed destination prevents integrated travel."),
        ("Sharing, connection and privacy",
            "Enter your private group's server URL, password and display alias in Settings > Sharing. Blank aliases use Anonymous. Joining loads the server train; use Upload saved local marks/watches explicitly when needed. Offline shared-row edits are replaced by server state on reconnect.\n\n" +
            "Train sharing includes marks, order, dead state, flags and spicing. Everyone sharing the train can edit or reset it. Sightings share live positions/health and mapping evidence. Witnessed S kills update the group's timer. Community-source credentials are configured on the server.\n\n" +
            "The Connection icon in /hh shows connection status, Faloop freshness and feed coverage, with a shortcut to Settings > Sharing. Online scouts and connection controls remain there. Do not include passwords, webhook URLs or private character information in public logs or screenshots."),
        ("Discord setup",
            "Create a webhook in Discord through Channel Settings > Integrations > Webhooks, then add its URL in Settings > Discord. Disabled entries remain saved but receive no posts. Send test message posts to enabled entries. Train > Reports previews the selected report and shows the message count per enabled destination. Scout reports put the import code first and fit into one message when possible, or two messages with the code first and the report second. Completed-train reports summarize respawn ranges and retain sniped, missing and unknown-time details. If some messages or destinations succeed and others fail, inspect Discord before retrying to avoid duplicate posts."),
        ("Trigger counters and lifetime tally",
            "Select a mark in S-ranks > Counters for trigger-mob totals on that mark's world and instance. Current-zone observations, including Narrow-rift and Nunyunuwi, require that exact location. S-ranks > All counters retains the full world and instance browser; /hhc shows counters for your current zone. Settings > Counters controls kill counting. Train > Plan > S-rank watch setup manages train checks; eligible marks also expose Train watch in their selected details. Trigger counters measure progress for a spawn attempt. Mine shows locally recorded personal events; Nearby shows locally recorded nearby kills when that counting mode is enabled. Group is the separate shared total. Shared counts use personal contributions so nearby observers do not double-count. Reset local affects only your selected world and instance; Reset group starts a new group attempt and discards pending contributions for the old attempt. Reset all local counts asks for confirmation and clears all stored trigger counts on this client, without changing group counts or lifetime tallies.\n\n" +
            "The lifetime tally is separate and stored per character. Settings > Tally selects ranks, kill-credit detection and reward confirmation. Damage-based credit follows your actions but does not prove sufficient contribution for rewards. If unavailable, combat-based detection is used; strict credit also checks targeting and the mark’s combat state. Reward confirmation waits for the game’s contribution message; B ranks are exempt. Watching distance controls when tracking starts. IPC reporting options affect what other plugins receive.\n\n" +
            "Achievement seeding imports cumulative totals without per-mark detail. Review baseline and drift before applying corrections; achievement matching uses names and ranks. The detail-log limit removes old timestamped entries, not lifetime totals. Export filtered CSV in Tally > Marks exports the selected character scope, rank and name filter; All characters exports the combined per-mark counts shown in the table. Achievement baselines are excluded because they have no per-mark detail. Tally reset has its own confirmation. A separate installed Hunt Tally disables the built-in tally until removed and HHE reloaded."),
    ];

    private void DrawHelpPage()
    {
        if (ImGui.Button("Release notes")) _releaseNotesVisible = true;
        ImGui.SameLine();
        ImGui.TextDisabled($"Version {ReleaseNotes.CurrentVersion}");
        ImGui.Spacing();
        ImGui.SetNextItemWidth(-1);
        ImGui.InputTextWithHint("##Help search", "Search UI help…", ref _helpSearch, 100);
        if (ImGui.BeginChild("Help topics", new Vector2(0, 0), false))
        {
            var query = _helpSearch.Trim();
            var found = false;
            foreach (var (title, text) in HelpTopics)
            {
                if (query.Length > 0 && !title.Contains(query, StringComparison.OrdinalIgnoreCase)
                    && !text.Contains(query, StringComparison.OrdinalIgnoreCase)) continue;
                found = true;
                if (query.Length > 0)
                {
                    DrawSettingsHeading(title);
                    ImGui.TextWrapped(text);
                    ImGui.Spacing();
                }
                else if (ImGui.CollapsingHeader(title))
                {
                    ImGui.TextWrapped(text);
                    ImGui.Spacing();
                }
            }
            if (!found) ImGui.TextDisabled("No matching help topics.");
        }
        ImGui.EndChild();
    }
}
